sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: nPyr129mtMdtEpJJE47ZGaxsKOFVtJRlDpQHv2UYuIHBVLsS2a8wpHw9Czv6Hlx/AK67a+X2DAd2226Boeh06NF7HVIbU6CPieMJA6cJkz/2x6B2faMJuOegYVRJ09/tX/qNn0dhodB2TdnD1CtVs9yKsGFOoyn8cLk+BTxUfZmDJUMLWzt5Is6ps4JyH455jm0WVIEn4+Kh0++U7Tne/Lt0ewQWyn5EHouZorW+MnvN4DMmoPKffzI+hjla7SpxJz8VreQVEGABrxbJLZ5bNWM4uAN0zKaZxRq+55MmYcbNAS3uDSwhDOQuB4f7nEiboCNIW/fQVMm846iinZAkI53WIKN3obY3DGOQMShCRB9RLtipXCVvLaJLcygFgb8yCz4Rbp6jJptU3CB4phEhV/yteafc7v2cpMPBd4PkamzuJusH26ij/wSt/QXYSi6ZhIGxT83igUcvGsO7PoNZqj9m2IFR/O+98aQMHUqvEG5gvfxhitHm+0ISsJm7m99i8b0Y8aV0/aFhhjvWrgthqJ/cnf0fH9ZyBF77Xgif2Gf9NokWnlHfgFV0/iSOZo8rSvY6BheP6f2R2fzTu2q4LQdz+R4iOlmdmCvpmAyIpxW2uge1pDO7Kb628Ngx51x7IYwWdEPdXMMx+EgDMMa6VxdN/pmtgP7WCxUXYW8SqEI=}, {secure: gpD2y9pjuHTWj/RFeXZlWd5o9PDC/rlOb2Kmx1w7r9QjK/bQ+l4ke2FY/Pk/ePxwcpdn6rDk77jAtdBFW0PFThRuotgtKbhR4eteBs2a6Rl9rs2AD0QSo0vbXBpF5RQjk9oLRuIKTg7Y8Cw3TSLjJongqlqMQUgbW9f9lYdlwgkmZlE1rD2x7n3Mtq/51KJ7NWI9+0AXmPli4Ol0Cnz1YBIEU0mq+otSyi+gxH6ImQSkjuUT1Hfmkh5Ph/nxJUyE3Kc6kI5tadTjQsICLCHZwSMwZwH0rZbwex1+FyOCMVzLWQTNrrPqSKaxi4OdICu1nExNokWfDSO+PjlnSyfX+UVE6zxmdF58175uWAxLAuF3puIIHkhlTkpzU9Lf1EzflIx2ZJ6g1MpTEC0XIPp4gqXkare3StFQssDfp4NjqiokbvPRDsYoQBVxTmWWy9hfDcT0YrwyHZW7YKgSBiAhjLJh/qx0qvzK1Yai/BvxnXGLKRd6jWFAA3jYbsgyX+jbV8e4Jv5/jz2ZzeUXL1YRFUzODzooZebwROrOuWs6Q4OEooAUeBv8/yAO3EuxR8yqMiMURYpHvlPoQN6R3fdSU+4Z6TzCcCLT3ssYE0hbW1JPoHTR/BWXqRQ4Ren3kBDYm3ZvnOib+8EExx7FCOZNqs7i5zStTqzKBojiV51FSmE=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
